name: Pylint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
    build: 
      runs-on: ubuntu-22.04
      strategy:
        matrix:
          python-version: ["3.10", "3.11"]

      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
         python-version: ${{ matrix.python-version }}
         cache: 'pip'
         path: ${{ env.pythonLocation }}
         key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Analysing the code with pylint, black and pycodestyle  
        run: python -m pip install --upgrade pip      
      - name: Install project requirements  
        run: python -m pip install -r requirements.txt
      - name: Install black, pylint, pycodestyle linters  
        run: pip install pylint==v2.17.3 pycodestyle==2.10.0
      #- name: apply black linter black==22.3.0 
      #  run: black $(git ls-files '*.py')
      - name: apply pylint linter
        run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')
      - name: apply pycodestyle linter
        run: pycodestyle $(git ls-files '*.py')
